### ISSUE TITLE
UI change in menu-items

### ISSUE THREAD

**Issue by om-ghumare** [shashank1503-cipher/partners-in-crime#40]
Font color change of the sign-out  button to differentiate between other buttons

**Comment by shashank1503-cipher** [comment]
Can you send a screenshot for that

**Comment by shashank1503-cipher** [comment]
Send a PR and will review it, and will merge if it is a better change

Thanks for contributing :)

**Comment by om-ghumare** [comment]
![image](https://user-images.githubusercontent.com/77767854/194046212-3efdcfec-ec33-435d-9921-3bd66d35a0bb.png)
![image](https://user-images.githubusercontent.com/77767854/194046289-d0b0a3d2-29f2-41a0-bc29-f33843f2b7a5.png)


there is a gap between  signout button and other buttons to differentiate but I think changing the font color of it will improve the UI
